### ISSUE TITLE
Global top artists, songs, albums, etc.

### ISSUE THREAD

**Issue by Vanmax22** [fmbot-discord/fmbot#117]
**What command would you like to see improved or added?**
It would be nice if there was a command that allowed you to view a global top artist, song, or album.

**What exactly should it do?**
It should act like .fmserveralbums but instead show data from all the servers that .fmbot is in

**Comment by th0mk** [comment]
I've considered adding this before, but it has some disadvantages:
- People will try to manipulate bot wide charts, possibly by registering multiple times and fake scrobbling. I don't want to moderate this or invest too much time into that stuff. It's the reason I don't really have any global commands
- When someone manipulates the charts people will come to me asking what user has 99999 scrobbles of song xyz so they want a global whoknows, which won't happen because it will lead to even more moderation
- It will be resource intensive (but this can be solved with caching)

I might consider adding this as a hidden command for those that really want it. Maybe with a big disclaimer about cheaters

**Comment by th0mk** [comment]
This feature has been added.
