### ISSUE TITLE
Guard against mistaken fmset commands clearing a user's crowns

### ISSUE THREAD

**Issue by rzumer** [fmbot-discord/fmbot#120]
**What command would you like to see improved or added?**
`fmset`

**What exactly should it do?**
I've seen several people inadvertently change their username via `fmset` and clear their crown count as a result, which then requires manually checking every artist to claim them again.

The command should ask for a confirmation if a username is already set, or cache previous usernames's crown counts so that they may be restored when mistaken username changes are corrected.

**Comment by th0mk** [comment]
I now consider the `.fmset` command legacy since it has been replaced by `.fmlogin` and `.fmmode`. This is done for multiple reasons, but mostly since Last.fm said they would prefer if we authenticated our users to help with the API rate limiting on their side. 

`.fmset` will keep existing, but I will add some warnings to it that using the command will clear your crowns. I don't really want people to use `.fmset` anymore, I also stopped mentioning it everywhere and the only place you can find it is in our docs under the `misc` commands. All commands should support using mentions to do commands for other Last.fm users, most commands already do but I'm working on getting this supported everywhere.

`.fmlogin` also has the advantage that a user can prove that they actually own a Last.fm account, so clearing the crowns would not be needed. This is something I will change as well.

**Comment by th0mk** [comment]
Changes described above have been released, you can now use `.fmlogin` if you changed your username and you will not lose any crowns. The help descriptions for `.fmset` have also been expanded with a warning.
