### ISSUE TITLE
Auto check for crowns

### ISSUE THREAD

**Issue by nopeinomicon** [fmbot-discord/fmbot#124]
**What command would you like to see improved or added?**
I would like it if the the bot was able to automatically check for crowns, in the same manner as something like [Chuu bot](https://github.com/ishwi/Chuu), without requiring the user to individually check every artist.

**What exactly should it do?**
The bot should automatically detect which crowns a user has without requiring a command input for each artist the user would like to obtain a crown for.

**Comment by th0mk** [comment]
The way I was thinking of adding this is by adding a command that will automatically check all artists for a server and seed the crowns for it. This would be a one time command, but people can re-do it later if they want. Also automatic crowns will be flagged so in the database so users can remove them for their server and do it again if they want.

Does this sound like an implementation you would be happy with? It's a bit different from Chuu since Chuu seems to check every single artist every time someone does !crowns. That would be too slow and it would basically require crowns to work a lot differently.

**Comment by nopeinomicon** [comment]
That would be great honestly. Maybe for resources this could be limited to like once every day or so on each server. I'd say maybe the .fmupdate command could also auto check for crowns with any artists that have changed or something along those lines.

**Comment by th0mk** [comment]
I have added this as `.fmcrownseeder`. 

To view how it works, use `.fmcrownseeder help`.
