### ISSUE TITLE
Ability to display arbitrary messages

### ISSUE THREAD

**Issue by CaseyAllen** [fmbot-discord/fmbot#191]
**Command to reproduce & Last.FM username:**

**Describe the bug:**
Using the lastfm Api, you can set your listening status to any text you want to,

the solution would be to sensor any text displayed in the listening status, however,
some songs have profanity in their titles, so it might be better to do a lookup on the Spotify API to see if the song exists, and if not, to display as nothing being listened to

**Version: ?**

**Comment by th0mk** [comment]
Hi, because of this reason we always show whoever executes the commands that show content from a Last.fm profile. Plus it's easy to see which Discord user the Last.fm account is connected to. This way server staff can always clearly see who is responsible for possible bad content and take appropriate action.

Regarding filtering through Spotify I would rather not do that. Spotify has plenty of titles with profanity. Plus not all music people scrobble is on Spotify.

Dealing with user generated content like this can be tricky. There is no 100% guaranteed way to never show bad content, but we make a best effort. I don't think we need to add additional safeguards like filtering to our commands right now, but am ofcourse always open to feedback.
